export const motivationalQuotes = [
    "Stay focused, ignore distractions, and execute relentlessly. 🎯",
    "Discipline is choosing between what you want now and what you want most. 🔥",
    "Your focus determines your reality. Keep your eyes on the goal. 🎯",
    "Push yourself because no one else is going to do it for you. 💪",
    "If it doesn’t challenge you, it won’t change you. 🔥",
    "You didn’t come this far to only come this far. 🚀",
    "Losers quit when they’re tired. Winners quit when they’ve won. 🏆",
    "Success is the result of consistent focus and relentless effort. ⚡",
    "Make distractions afraid of your focus. 🔥",
    "Your future is created by what you do today, not tomorrow. ⏳",
    "Do what needs to be done, even when you don’t feel like it. 💯",
    "One hour of deep work is better than five hours of distraction. 🚀",
    "Don’t count the days, make the days count. 📆",
    "Mindset is what separates the best from the rest. 🧠",
    "Hard work beats talent when talent doesn’t work hard. 💪",
    "Train your mind to stay focused, and everything else will follow. 🎯",
    "The pain of discipline is better than the pain of regret. 🔥",
    "Focus like a sniper, execute like a machine. 🎯🤖",
    "Small consistent actions lead to massive results. 📈",
    "You become what you repeatedly do. Focus on excellence. 💯",
    "Don’t let a bad day make you feel like you have a bad life. ☀️",
    "No more excuses. Get it done. 🚀",
    "Great things take time, but they require daily effort. ⏳",
    "Cut out distractions and focus on your next move. 🔥",
    "If you want different results, do something different. 🎯",
    "A dream without a plan is just a wish. Make a plan and execute. 📋",
    "Work in silence, let success make the noise. 🤫🔥",
    "You will never always be motivated, so learn to be disciplined. 💪",
    "Stay patient, stay focused, and trust the process. 🔄",
    "The only limit is the one you set in your mind. 🚀",
    "Focus on progress, not perfection. 🎯",
    "Every second you waste is a second closer to failure. ⏳",
    "Get comfortable with being uncomfortable. That’s where growth happens. 🔥",
    "Winners focus on winning, losers focus on winners. 🎯",
    "If you fail to plan, you plan to fail. 📝",
    "Make today so productive that your future self thanks you. ⏳",
    "Distraction is the enemy of progress. Guard your focus. 🔥",
    "One focused hour is better than an entire day of multitasking. ⏳",
    "Either you run the day, or the day runs you. 💪",
    "You can have excuses or results, but not both. Choose wisely. 🎯",
    "Success is 90% mindset, 10% execution. Train both. 🧠⚡",
    "Burn your excuses, build your results. 🔥",
    "Every champion was once a beginner who refused to give up. 🏆",
    "Consistency is the bridge between goals and success. 🌉",
    "You don’t need more time, you need more focus. ⏳",
    "Fear kills more dreams than failure ever will. Face it. 🚀",
    "Turn your distractions into motivation. 💡",
    "If you're tired, do it tired. Just get it done. ⚡",
    "You owe it to yourself to become everything you’ve dreamed of. 🔥",
    "Focus on what you can control, and execute with precision. 🎯",
    "The road to success is always under construction. Keep building. 🚀",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. 🏆",
    "Dream big, work hard, stay focused, and surround yourself with good people. 💪",
    "Winners never quit, and quitters never win. 🎯",
    "Your mindset determines your success. Train it well. 🧠",
    "Success doesn’t come from what you do occasionally, but from what you do consistently. 🔥",
    "The secret to success? Stop wishing, start doing. 🚀",
    "Doubt kills more dreams than failure ever will. Believe in yourself. 💯",
    "Success is the sum of small efforts, repeated day in and day out. ⏳",
    "A goal without action is just a wish. Take action today. 🎯",
    "Surround yourself with people who push you to be better. 🤝",
    "Your energy introduces you before you even speak. Stay positive. ⚡",
    "The best revenge is massive success. Let your results speak. 🔥",
    "If it was easy, everyone would do it. Keep grinding. 💪",
    "Stop waiting for the perfect moment. Take the moment and make it perfect. ⏳",
    "Action is the foundational key to all success. Start now. 🚀",
    "Success is a decision. Make it yours. 🎯",
    "Keep your eyes on the stars and your feet on the ground. 🌟",
    "Difficult roads often lead to beautiful destinations. Keep going. 🛤️",
    "The only way to predict the future is to create it. 💡",
    "Excuses make zero progress. Execution makes all the difference. 🔥",
    "Work so hard that your idols become your rivals. 💪",
    "A year from now, you’ll wish you started today. ⏳",
    "Nothing works unless you do. Stay disciplined. ⚡",
    "You get what you work for, not what you wish for. 💯",
    "Believe in yourself and you’re halfway there. 🚀",
    "Hustle in silence and let success make the noise. 🎯",
    "Success is about consistency, not intensity. Keep moving forward. ⏳",
    "To achieve greatness, stop asking for permission. 🔥"

  ];
  