export const wallpapers = [
    require("../assets/wallpapers/wallpaper1.jpg"),
    require("../assets/wallpapers/wallpaper2.jpg"),
    require("../assets/wallpapers/wallpaper3.jpg"),
    require("../assets/wallpapers/wallpaper4.jpg"),
    require("../assets/wallpapers/wallpaper5.jpg"),
    require("../assets/wallpapers/wallpaper6.jpg"),
    require("../assets/wallpapers/wallpaper7.jpg"),
    require("../assets/wallpapers/wallpaper8.jpg"),
    require("../assets/wallpapers/wallpaper9.jpg"),
    require("../assets/wallpapers/wallpaper10.jpg"),
    require("../assets/wallpapers/wallpaper11.jpg"),
    require("../assets/wallpapers/wallpaper12.jpg"),
    require("../assets/wallpapers/wallpaper16.jpg"),
    require("../assets/wallpapers/wallpaper13.jpg"),
    require("../assets/wallpapers/wallpaper14.jpg"),
    require("../assets/wallpapers/wallpaper15.jpg"),
    require("../assets/wallpapers/wallpaper17.jpg"),
    require("../assets/wallpapers/wallpaper18.jpg"),
    require("../assets/wallpapers/wallpaper19.jpg"),
    require("../assets/wallpapers/wallpaper20.jpg"),
    require("../assets/wallpapers/wallpaper21.jpg"),
    require("../assets/wallpapers/wallpaper22.jpg"),
    require("../assets/wallpapers/wallpaper23.jpg"),
    require("../assets/wallpapers/wallpaper24.jpg"),
    require("../assets/wallpapers/wallpaper25.jpg"),
    require("../assets/wallpapers/wallpaper26.jpg"),
    require("../assets/wallpapers/wallpaper27.jpg"),
    require("../assets/wallpapers/wallpaper28.jpg"),
    require("../assets/wallpapers/wallpaper29.jpg"),
    require("../assets/wallpapers/wallpaper30.jpg"),
    require("../assets/wallpapers/wallpaper31.jpg"),
    require("../assets/wallpapers/wallpaper32.jpg"),
    require("../assets/wallpapers/wallpaper33.jpg"),
    require("../assets/wallpapers/wallpaper34.jpg"),
    require("../assets/wallpapers/wallpaper35.jpg"),
    

  ];


  export const wallpapersObj = {
    wallpaper1: require("../assets/wallpapers/wallpaper1.jpg"),
    wallpaper2: require("../assets/wallpapers/wallpaper2.jpg"),
    wallpaper3: require("../assets/wallpapers/wallpaper3.jpg"),
    wallpaper4: require("../assets/wallpapers/wallpaper4.jpg"),
    wallpaper5: require("../assets/wallpapers/wallpaper5.jpg"),
    wallpaper6: require("../assets/wallpapers/wallpaper6.jpg"),
    wallpaper7: require("../assets/wallpapers/wallpaper7.jpg"),
    wallpaper8: require("../assets/wallpapers/wallpaper8.jpg"),
    wallpaper9: require("../assets/wallpapers/wallpaper9.jpg"),
    wallpaper10: require("../assets/wallpapers/wallpaper10.jpg"),
    wallpaper11: require("../assets/wallpapers/wallpaper11.jpg"),
    wallpaper12: require("../assets/wallpapers/wallpaper12.jpg"),
    wallpaper13: require("../assets/wallpapers/wallpaper13.jpg"),
    wallpaper14: require("../assets/wallpapers/wallpaper14.jpg"),
    wallpaper15: require("../assets/wallpapers/wallpaper15.jpg"),
    wallpaper16: require("../assets/wallpapers/wallpaper16.jpg"),
    wallpaper17: require("../assets/wallpapers/wallpaper17.jpg"),
    wallpaper18: require("../assets/wallpapers/wallpaper18.jpg"),
    wallpaper19: require("../assets/wallpapers/wallpaper19.jpg"),
    wallpaper20: require("../assets/wallpapers/wallpaper20.jpg"),
    wallpaper21: require("../assets/wallpapers/wallpaper21.jpg"),
    wallpaper22: require("../assets/wallpapers/wallpaper22.jpg"),
    wallpaper23: require("../assets/wallpapers/wallpaper23.jpg"),
    wallpaper24: require("../assets/wallpapers/wallpaper24.jpg"),
    wallpaper25: require("../assets/wallpapers/wallpaper25.jpg"),
    wallpaper26: require("../assets/wallpapers/wallpaper26.jpg"),
    wallpaper27: require("../assets/wallpapers/wallpaper27.jpg"),
    wallpaper28: require("../assets/wallpapers/wallpaper28.jpg"),
    wallpaper29: require("../assets/wallpapers/wallpaper29.jpg"),
    wallpaper30: require("../assets/wallpapers/wallpaper30.jpg"),
    wallpaper31: require("../assets/wallpapers/wallpaper31.jpg"),
    wallpaper32: require("../assets/wallpapers/wallpaper32.jpg"),
    wallpaper33: require("../assets/wallpapers/wallpaper33.jpg"),
    wallpaper34: require("../assets/wallpapers/wallpaper34.jpg"),
    wallpaper35: require("../assets/wallpapers/wallpaper35.jpg"),
  };
  